from flask import Flask, render_template, request
from textwrap import dedent
import openai
import os

app = Flask(__name__)
prompt = ""

def openai_ui(prompt):
    openai.api_key = os.environ['OPENAI_KEY']

    try:
        response = openai.Completion.create(
            engine="text-davinci-003",
            prompt=prompt,
            max_tokens=256,
            temperature=0.6,
            top_p=1.0,
            frequency_penalty=0,
            presence_penalty=0.5
        )

        return response.choices[0].text
    except openai.OpenAIException as e:
            return "Error: {}".format(str(e))

@app.route('/')
def index():
    title = 'Hello!'
    html = '''
        <p>The next page is generated by OpenAI API</p>
        <p><a href="/interview" class="text-lg text-blue-600 hover:text-blue-700 underline">Show me!</a></p>
    '''
    return render_template('base.html', title=title, content=html)

@app.route('/interview', methods=['GET', 'POST'])
def interview():
    global prompt
    if request.method == 'GET':
        prompt = dedent("""
        Beautiful HTML styled with TailwindCSS to collect one answer for a question to evaluate a Senior Software Engineer candidate interviewing at a startup.
        Form action='/interview', method='post'.
        Element named: `q`
        """).strip("\n")

        title = "Interview"
        html = openai_ui(prompt)
        prompt += "\n{}\n".format(html)

        return render_template('base.html', title=title, content=html)
    else:
        q = request.form['q'].strip()
        prompt += dedent("""
        Evaluate the candidate's answer and give some thoughtful feedback. Output as HTML element styled with TailwindCSS.
        Candidate answer: {}
        Output:
        """).format(q).strip("\n")

        title = "Feedback"
        html = openai_ui(prompt)
        return render_template('base.html', title=title, content=html)

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5000)

